In [ ]:
# ćwiczenie 1
# utwórz nowy notatnik z ćwiczeniami
# Otwórz plik Excela "test.xlsx" i wyeksportuj do "test.csv", i wypisz 10 ostatnich wierszy
# z df wypisz wiersze od 100 do 1000 co 20 wiersz
# zapisz w nowym df1, zresetuj indeksy , wybierz parzyste wiersze i kolumny

In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("test.xlsx")

In [3]:
df.to_csv("test_2.csv")

In [4]:
df.tail(10)

        Unnamed: 0  Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
145279      145279    2016     131   1392      80   1436      74    H      0
145280      145280    2016     131   1401      71   1261      38    N      0
145281      145281    2016     131   1419      82   1426      71    N      0
145282      145282    2016     131   1433      76   1172      54    N      0
145283      145283    2016     131   1451      62   1285      59    N      0
145284      145284    2016     132   1114      70   1419      50    N      0
145285      145285    2016     132   1163      72   1272      58    N      0
145286      145286    2016     132   1246      82   1401      77    N      1
145287      145287    2016     132   1277      66   1345      62    N      0
145288      145288    2016     132   1386      87   1433      74    N      0

In [5]:
df.iloc[100:1000:20]

     Unnamed: 0  Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
100         100    1985      29   1409      86   1331      82    A      0
120         120    1985      30   1437      56   1265      51    A      0
140         140    1985      32   1112      84   1409      80    H      0
160         160    1985      32   1359      93   1218      84    A      0
180         180    1985      33   1129      54   1186      49    A      0
200         200    1985      33   1229      54   1283      44    H      0
220         220    1985      33   1277      76   1119      64    H      0
240         240    1985      33   1376      79   1406      68    H      0
260         260    1985      34   1130      82   1448      76    N      0
280         280    1985      35   1360      65   1363      63    H      0
300         300    1985      36   1192      61   1134      46    A      0
320         320    1985      36   1398      80   1212      65    H      0
340         340    1985      37   1265      73   1351      68    A      0
360         360    1985      37   1427      72   1168      64    H      0
380         380    1985      38   1449      68   1388      48    H      0
400         400    1985      39   1378      87   1197      59    H      0
420         420    1985      40   1155      89   1121      62    H      0
440         440    1985      40   1233      74   1226      69    H      0
460         460    1985      40   1299     110   1288      69    H      0
480         480    1985      40   1373      73   1306      66    A      0
500         500    1985      40   1435      84   1124      81    A      0
520         520    1985      42   1256      73   1123      59    H      0
540         540    1985      43   1200      74   1371      70    H      0
560         560    1985      44   1120      79   1347      57    H      0
580         580    1985      44   1385      77   1172      51    N      0
600         600    1985      46   1397      89   1379      73    H      0
620         620    1985      47   1191      72   1114      65    H      0
640         640    1985      47   1257      71   1246      64    H      0
660         660    1985      47   1351      71   1383      66    H      0
680         680    1985      47   1427      69   1341      58    A      0
700         700    1985      49   1211      78   1286      65    H      0
720         720    1985      50   1210      81   1299      43    H      0
740         740    1985      51   1192      55   1344      53    A      0
760         760    1985      52   1285      60   1168      59    A      0
780         780    1985      53   1199      83   1338      76    N      0
800         800    1985      53   1390      67   1258      59    H      0
820         820    1985      54   1178      77   1278      67    A      0
840         840    1985      54   1239      71   1279      47    H      0
860         860    1985      54   1332      55   1308      51    A      0
880         880    1985      54   1429      94   1226      85    A      0
900         900    1985      58   1234      59   1165      56    N      0
920         920    1985      59   1375      90   1106      85    H      0
940         940    1985      60   1181      76   1412      62    N      0
960         960    1985      60   1330      82   1353      80    N      0
980         980    1985      60   1424      77   1243      68    H      0

In [6]:
df1 = df.iloc[100:1000:20]
df1 = df1.reset_index()
df1

,index,Unnamed: 0,Season,Daynum,Wteam,Wscore,Lteam,Lscore,Wloc,Numot
0,100,100,1985,29,1409,86,1331,82,A,0
1,120,120,1985,30,1437,56,1265,51,A,0
2,140,140,1985,32,1112,84,1409,80,H,0
3,160,160,1985,32,1359,93,1218,84,A,0
4,180,180,1985,33,1129,54,1186,49,A,0
5,200,200,1985,33,1229,54,1283,44,H,0
6,220,220,1985,33,1277,76,1119,64,H,0
7,240,240,1985,33,1376,79,1406,68,H,0
8,260,260,1985,34,1130,82,1448,76,N,0
9,280,280,1985,35,1360,65,1363,63,H,0
10,300,300,1985,36,1192,61,1134,46,A,0
11,320,320,1985,36,1398,80,1212,65,H,0
12,340,340,1985,37,1265,73,1351,68,A,0
13,360,360,1985,37,1427,72,1168,64,H,0
14,380,380,1985,38,1449,68,1388,48,H,0
15,400,400,1985,39,1378,87,1197,59,H,0
16,420,420,1985,40,1155,89,1121,62,H,0
17,440,440,1985,40,1233,74,1226,69,H,0
18,460,460,1985,40,1299,110,1288,69,H,0
19,480,480,1985,40,1373,73,1306,66,A,0
20,500,500,1985,40,1435,84,1124,81,A,0
21,520,520,1985,42,1256,73,1123,59,H,0
22,540,540,1985,43,1200,74,1371,70,H,0
23,560,560,1985,44,1120,79,1347,57,H,0
24,580,580,1985,44,1385,77,1172,51,N,0
25,600,600,1985,46,1397,89,1379,73,H,0
26,620,620,1985,47,1191,72,1114,65,H,0
27,640,640,1985,47,1257,71,1246,64,H,0
28,660,660,1985,47,1351,71,1383,66,H,0
29,680,680,1985,47,1427,69,1341,58,A,0
30,700,700,1985,49,1211,78,1286,65,H,0
31,720,720,1985,50,1210,81,1299,43,H,0
32,740,740,1985,51,1192,55,1344,53,A,0
33,760,760,1985,52,1285,60,1168,59,A,0
34,780,780,1985,53,1199,83,1338,76,N,0
35,800,800,1985,53,1390,67,1258,59,H,0
36,820,820,1985,54,1178,77,1278,67,A,0
37,840,840,1985,54,1239,71,1279,47,H,0
38,860,860,1985,54,1332,55,1308,51,A,0
39,880,880,1985,54,1429,94,1226,85,A,0
40,900,900,1985,58,1234,59,1165,56,N,0
41,920,920,1985,59,1375,90,1106,85,H,0
42,940,940,1985,60,1181,76,1412,62,N,0
43,960,960,1985,60,1330,82,1353,80,N,0
44,980,980,1985,60,1424,77,1243,68,H,0

In [8]:
# wybrać parzyste wiersze i kolumny
df.iloc[::2, ::2]

        Unnamed: 0  Daynum  Wscore  Lscore  Numot
0                0      20      81      64      0
2                2      25      63      56      0
4                4      25      86      74      0
6                6      25      64      44      0
8                8      25      98      80      0
...            ...     ...     ...     ...    ...
145280      145280     131      71      38      0
145282      145282     131      76      54      0
145284      145284     132      70      50      0
145286      145286     132      82      77      1
145288      145288     132      87      74      0

[72645 rows x 5 columns]

In [9]:
df.sort_values?